// TODO message结构的属性名请使用 驼峰小写字母开始
// TODO enum枚举的属性名请使用 驼峰大写字母开始

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/protocol/base_error.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 响应错误
// 当客户端发送Request类型消息时，如果有异常则返回ErrorResponse
// 踢下线协议也会用到该结构
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 错误内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_internal_protocol_base_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_base_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_base_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_protocol_base_error_proto protoreflect.FileDescriptor

const file_internal_protocol_base_error_proto_rawDesc = "" +
	"\n" +
	"\"internal/protocol/base_error.proto\x12\x02pb\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\x05Z\x03/pbb\x06proto3"

var (
	file_internal_protocol_base_error_proto_rawDescOnce sync.Once
	file_internal_protocol_base_error_proto_rawDescData []byte
)

func file_internal_protocol_base_error_proto_rawDescGZIP() []byte {
	file_internal_protocol_base_error_proto_rawDescOnce.Do(func() {
		file_internal_protocol_base_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_base_error_proto_rawDesc), len(file_internal_protocol_base_error_proto_rawDesc)))
	})
	return file_internal_protocol_base_error_proto_rawDescData
}

var file_internal_protocol_base_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_protocol_base_error_proto_goTypes = []any{
	(*ErrorResponse)(nil), // 0: pb.ErrorResponse
}
var file_internal_protocol_base_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protocol_base_error_proto_init() }
func file_internal_protocol_base_error_proto_init() {
	if File_internal_protocol_base_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_base_error_proto_rawDesc), len(file_internal_protocol_base_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_base_error_proto_goTypes,
		DependencyIndexes: file_internal_protocol_base_error_proto_depIdxs,
		MessageInfos:      file_internal_protocol_base_error_proto_msgTypes,
	}.Build()
	File_internal_protocol_base_error_proto = out.File
	file_internal_protocol_base_error_proto_goTypes = nil
	file_internal_protocol_base_error_proto_depIdxs = nil
}
