// TODO message结构的属性名请使用 驼峰小写字母开始
// TODO enum枚举的属性名请使用 驼峰大写字母开始

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/protocol/login.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登陆请求(建立连接后的第一条消息，验证通过后则进行后续流程)
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int32                  `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`                                                                       // 当前登陆的服务器id
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                                                              // 登陆token(web login api生成的base64字符串)
	Params        map[int32]string       `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 登陆时上传的参数 key: LoginParams
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_internal_protocol_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *LoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginRequest) GetParams() map[int32]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// 登陆响应
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                                                 // 游戏内的用户唯一id
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`                                                                                 // 平台id
	OpenId        string                 `protobuf:"bytes,3,opt,name=openId,proto3" json:"openId,omitempty"`                                                                            // 平台openId(平台的帐号唯一id)
	Params        map[int32]string       `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 登陆后的扩展参数，按需增加
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_internal_protocol_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LoginResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *LoginResponse) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *LoginResponse) GetParams() map[int32]string {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_internal_protocol_login_proto protoreflect.FileDescriptor

const file_internal_protocol_login_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/protocol/login.proto\x12\x02pb\"\xb1\x01\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\bserverId\x18\x01 \x01(\x05R\bserverId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x124\n" +
	"\x06params\x18\x05 \x03(\v2\x1c.pb.LoginRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\rLoginResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06openId\x18\x03 \x01(\tR\x06openId\x125\n" +
	"\x06params\x18\x04 \x03(\v2\x1d.pb.LoginResponse.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x05Z\x03/pbb\x06proto3"

var (
	file_internal_protocol_login_proto_rawDescOnce sync.Once
	file_internal_protocol_login_proto_rawDescData []byte
)

func file_internal_protocol_login_proto_rawDescGZIP() []byte {
	file_internal_protocol_login_proto_rawDescOnce.Do(func() {
		file_internal_protocol_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_login_proto_rawDesc), len(file_internal_protocol_login_proto_rawDesc)))
	})
	return file_internal_protocol_login_proto_rawDescData
}

var file_internal_protocol_login_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_protocol_login_proto_goTypes = []any{
	(*LoginRequest)(nil),  // 0: pb.LoginRequest
	(*LoginResponse)(nil), // 1: pb.LoginResponse
	nil,                   // 2: pb.LoginRequest.ParamsEntry
	nil,                   // 3: pb.LoginResponse.ParamsEntry
}
var file_internal_protocol_login_proto_depIdxs = []int32{
	2, // 0: pb.LoginRequest.params:type_name -> pb.LoginRequest.ParamsEntry
	3, // 1: pb.LoginResponse.params:type_name -> pb.LoginResponse.ParamsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_protocol_login_proto_init() }
func file_internal_protocol_login_proto_init() {
	if File_internal_protocol_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_login_proto_rawDesc), len(file_internal_protocol_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_login_proto_goTypes,
		DependencyIndexes: file_internal_protocol_login_proto_depIdxs,
		MessageInfos:      file_internal_protocol_login_proto_msgTypes,
	}.Build()
	File_internal_protocol_login_proto = out.File
	file_internal_protocol_login_proto_goTypes = nil
	file_internal_protocol_login_proto_depIdxs = nil
}
