// TODO message结构的属性名请使用 驼峰小写字母开始
// TODO enum枚举的属性名请使用 驼峰大写字母开始

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/protocol/player.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家属性变化
type PlayerAttribute int32

const (
	PlayerAttribute_AA_AttributeNone PlayerAttribute = 0 // 未使用
)

// Enum value maps for PlayerAttribute.
var (
	PlayerAttribute_name = map[int32]string{
		0: "AA_AttributeNone",
	}
	PlayerAttribute_value = map[string]int32{
		"AA_AttributeNone": 0,
	}
)

func (x PlayerAttribute) Enum() *PlayerAttribute {
	p := new(PlayerAttribute)
	*p = x
	return p
}

func (x PlayerAttribute) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerAttribute) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_player_proto_enumTypes[0].Descriptor()
}

func (PlayerAttribute) Type() protoreflect.EnumType {
	return &file_internal_protocol_player_proto_enumTypes[0]
}

func (x PlayerAttribute) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerAttribute.Descriptor instead.
func (PlayerAttribute) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_player_proto_rawDescGZIP(), []int{0}
}

// 玩家基本信息
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`     // 玩家ID
	PlayerName    string                 `protobuf:"bytes,2,opt,name=playerName,proto3" json:"playerName,omitempty"`  // 玩家昵称
	Gender        int32                  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`         // 角色性别
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`           // 角色等级
	CreateTime    int64                  `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"` // 创建时间
	Exp           int64                  `protobuf:"varint,6,opt,name=exp,proto3" json:"exp,omitempty"`               // 经验值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_internal_protocol_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_internal_protocol_player_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Player) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *Player) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *Player) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Player) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Player) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

// 查询角色响应
type PlayerSelectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Player              `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"` // 玩家列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSelectResponse) Reset() {
	*x = PlayerSelectResponse{}
	mi := &file_internal_protocol_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSelectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSelectResponse) ProtoMessage() {}

func (x *PlayerSelectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSelectResponse.ProtoReflect.Descriptor instead.
func (*PlayerSelectResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_player_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerSelectResponse) GetList() []*Player {
	if x != nil {
		return x.List
	}
	return nil
}

// 请求创建角色
type PlayerCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=playerName,proto3" json:"playerName,omitempty"` // 玩家昵称
	Gender        int32                  `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"`        // 性别(0女,1男)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerCreateRequest) Reset() {
	*x = PlayerCreateRequest{}
	mi := &file_internal_protocol_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCreateRequest) ProtoMessage() {}

func (x *PlayerCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCreateRequest.ProtoReflect.Descriptor instead.
func (*PlayerCreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_player_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerCreateRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerCreateRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

// 创建角色回应
type PlayerCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"` // 玩家信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerCreateResponse) Reset() {
	*x = PlayerCreateResponse{}
	mi := &file_internal_protocol_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCreateResponse) ProtoMessage() {}

func (x *PlayerCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCreateResponse.ProtoReflect.Descriptor instead.
func (*PlayerCreateResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_player_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerCreateResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

// 进入游戏响应
type PlayerEnterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuideMaps     map[int32]int32        `protobuf:"bytes,2,rep,name=guideMaps,proto3" json:"guideMaps,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 新手引导记录列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEnterResponse) Reset() {
	*x = PlayerEnterResponse{}
	mi := &file_internal_protocol_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEnterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEnterResponse) ProtoMessage() {}

func (x *PlayerEnterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEnterResponse.ProtoReflect.Descriptor instead.
func (*PlayerEnterResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_player_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerEnterResponse) GetGuideMaps() map[int32]int32 {
	if x != nil {
		return x.GuideMaps
	}
	return nil
}

var File_internal_protocol_player_proto protoreflect.FileDescriptor

const file_internal_protocol_player_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/protocol/player.proto\x12\x02pb\"\xa4\x01\n" +
	"\x06Player\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x03R\bplayerId\x12\x1e\n" +
	"\n" +
	"playerName\x18\x02 \x01(\tR\n" +
	"playerName\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\x05R\x06gender\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1e\n" +
	"\n" +
	"createTime\x18\x05 \x01(\x03R\n" +
	"createTime\x12\x10\n" +
	"\x03exp\x18\x06 \x01(\x03R\x03exp\"6\n" +
	"\x14PlayerSelectResponse\x12\x1e\n" +
	"\x04list\x18\x01 \x03(\v2\n" +
	".pb.PlayerR\x04list\"M\n" +
	"\x13PlayerCreateRequest\x12\x1e\n" +
	"\n" +
	"playerName\x18\x01 \x01(\tR\n" +
	"playerName\x12\x16\n" +
	"\x06gender\x18\x02 \x01(\x05R\x06gender\":\n" +
	"\x14PlayerCreateResponse\x12\"\n" +
	"\x06player\x18\x01 \x01(\v2\n" +
	".pb.PlayerR\x06player\"\x99\x01\n" +
	"\x13PlayerEnterResponse\x12D\n" +
	"\tguideMaps\x18\x02 \x03(\v2&.pb.PlayerEnterResponse.GuideMapsEntryR\tguideMaps\x1a<\n" +
	"\x0eGuideMapsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01*'\n" +
	"\x0fPlayerAttribute\x12\x14\n" +
	"\x10AA_AttributeNone\x10\x00B\x05Z\x03/pbb\x06proto3"

var (
	file_internal_protocol_player_proto_rawDescOnce sync.Once
	file_internal_protocol_player_proto_rawDescData []byte
)

func file_internal_protocol_player_proto_rawDescGZIP() []byte {
	file_internal_protocol_player_proto_rawDescOnce.Do(func() {
		file_internal_protocol_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_player_proto_rawDesc), len(file_internal_protocol_player_proto_rawDesc)))
	})
	return file_internal_protocol_player_proto_rawDescData
}

var file_internal_protocol_player_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protocol_player_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_protocol_player_proto_goTypes = []any{
	(PlayerAttribute)(0),         // 0: pb.PlayerAttribute
	(*Player)(nil),               // 1: pb.Player
	(*PlayerSelectResponse)(nil), // 2: pb.PlayerSelectResponse
	(*PlayerCreateRequest)(nil),  // 3: pb.PlayerCreateRequest
	(*PlayerCreateResponse)(nil), // 4: pb.PlayerCreateResponse
	(*PlayerEnterResponse)(nil),  // 5: pb.PlayerEnterResponse
	nil,                          // 6: pb.PlayerEnterResponse.GuideMapsEntry
}
var file_internal_protocol_player_proto_depIdxs = []int32{
	1, // 0: pb.PlayerSelectResponse.list:type_name -> pb.Player
	1, // 1: pb.PlayerCreateResponse.player:type_name -> pb.Player
	6, // 2: pb.PlayerEnterResponse.guideMaps:type_name -> pb.PlayerEnterResponse.GuideMapsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_protocol_player_proto_init() }
func file_internal_protocol_player_proto_init() {
	if File_internal_protocol_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_player_proto_rawDesc), len(file_internal_protocol_player_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_player_proto_goTypes,
		DependencyIndexes: file_internal_protocol_player_proto_depIdxs,
		EnumInfos:         file_internal_protocol_player_proto_enumTypes,
		MessageInfos:      file_internal_protocol_player_proto_msgTypes,
	}.Build()
	File_internal_protocol_player_proto = out.File
	file_internal_protocol_player_proto_goTypes = nil
	file_internal_protocol_player_proto_depIdxs = nil
}
