// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/protocol/private_chat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 私聊消息请求
type PrivateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUid     uint64                 `protobuf:"varint,1,opt,name=targetUid,proto3" json:"targetUid,omitempty"` // 目标用户ID
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`      // 消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateChatRequest) Reset() {
	*x = PrivateChatRequest{}
	mi := &file_internal_protocol_private_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateChatRequest) ProtoMessage() {}

func (x *PrivateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_private_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateChatRequest.ProtoReflect.Descriptor instead.
func (*PrivateChatRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_private_chat_proto_rawDescGZIP(), []int{0}
}

func (x *PrivateChatRequest) GetTargetUid() uint64 {
	if x != nil {
		return x.TargetUid
	}
	return 0
}

func (x *PrivateChatRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 私聊消息响应
type PrivateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateChatResponse) Reset() {
	*x = PrivateChatResponse{}
	mi := &file_internal_protocol_private_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateChatResponse) ProtoMessage() {}

func (x *PrivateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_private_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateChatResponse.ProtoReflect.Descriptor instead.
func (*PrivateChatResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_private_chat_proto_rawDescGZIP(), []int{1}
}

func (x *PrivateChatResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PrivateChatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 私聊消息推送
type PrivateChatPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUid     uint64                 `protobuf:"varint,1,opt,name=targetUid,proto3" json:"targetUid,omitempty"` // 目标用户ID
	FromUid       uint64                 `protobuf:"varint,2,opt,name=fromUid,proto3" json:"fromUid,omitempty"`     // 发送者ID
	FromName      string                 `protobuf:"bytes,3,opt,name=fromName,proto3" json:"fromName,omitempty"`    // 发送者昵称
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`      // 消息内容
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateChatPush) Reset() {
	*x = PrivateChatPush{}
	mi := &file_internal_protocol_private_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateChatPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateChatPush) ProtoMessage() {}

func (x *PrivateChatPush) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_private_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateChatPush.ProtoReflect.Descriptor instead.
func (*PrivateChatPush) Descriptor() ([]byte, []int) {
	return file_internal_protocol_private_chat_proto_rawDescGZIP(), []int{2}
}

func (x *PrivateChatPush) GetTargetUid() uint64 {
	if x != nil {
		return x.TargetUid
	}
	return 0
}

func (x *PrivateChatPush) GetFromUid() uint64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *PrivateChatPush) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *PrivateChatPush) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PrivateChatPush) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_internal_protocol_private_chat_proto protoreflect.FileDescriptor

const file_internal_protocol_private_chat_proto_rawDesc = "" +
	"\n" +
	"$internal/protocol/private_chat.proto\x12\x02pb\"L\n" +
	"\x12PrivateChatRequest\x12\x1c\n" +
	"\ttargetUid\x18\x01 \x01(\x04R\ttargetUid\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"C\n" +
	"\x13PrivateChatResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9d\x01\n" +
	"\x0fPrivateChatPush\x12\x1c\n" +
	"\ttargetUid\x18\x01 \x01(\x04R\ttargetUid\x12\x18\n" +
	"\afromUid\x18\x02 \x01(\x04R\afromUid\x12\x1a\n" +
	"\bfromName\x18\x03 \x01(\tR\bfromName\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestampB\x05Z\x03/pbb\x06proto3"

var (
	file_internal_protocol_private_chat_proto_rawDescOnce sync.Once
	file_internal_protocol_private_chat_proto_rawDescData []byte
)

func file_internal_protocol_private_chat_proto_rawDescGZIP() []byte {
	file_internal_protocol_private_chat_proto_rawDescOnce.Do(func() {
		file_internal_protocol_private_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_private_chat_proto_rawDesc), len(file_internal_protocol_private_chat_proto_rawDesc)))
	})
	return file_internal_protocol_private_chat_proto_rawDescData
}

var file_internal_protocol_private_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_protocol_private_chat_proto_goTypes = []any{
	(*PrivateChatRequest)(nil),  // 0: pb.PrivateChatRequest
	(*PrivateChatResponse)(nil), // 1: pb.PrivateChatResponse
	(*PrivateChatPush)(nil),     // 2: pb.PrivateChatPush
}
var file_internal_protocol_private_chat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protocol_private_chat_proto_init() }
func file_internal_protocol_private_chat_proto_init() {
	if File_internal_protocol_private_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_private_chat_proto_rawDesc), len(file_internal_protocol_private_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_private_chat_proto_goTypes,
		DependencyIndexes: file_internal_protocol_private_chat_proto_depIdxs,
		MessageInfos:      file_internal_protocol_private_chat_proto_msgTypes,
	}.Build()
	File_internal_protocol_private_chat_proto = out.File
	file_internal_protocol_private_chat_proto_goTypes = nil
	file_internal_protocol_private_chat_proto_depIdxs = nil
}
