// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/protocol/rpcs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 节点状态
type NodeState int32

const (
	NodeState_Open     NodeState = 0 // 开放状态,所有角色可以进入
	NodeState_Maintain NodeState = 1 // 维护状态,白名单角色可以进入
	NodeState_Closed   NodeState = 2 // 关闭状态,所有角色不可进入(同时踢除所有角色)
)

// Enum value maps for NodeState.
var (
	NodeState_name = map[int32]string{
		0: "Open",
		1: "Maintain",
		2: "Closed",
	}
	NodeState_value = map[string]int32{
		"Open":     0,
		"Maintain": 1,
		"Closed":   2,
	}
)

func (x NodeState) Enum() *NodeState {
	p := new(NodeState)
	*p = x
	return p
}

func (x NodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_rpcs_proto_enumTypes[0].Descriptor()
}

func (NodeState) Type() protoreflect.EnumType {
	return &file_internal_protocol_rpcs_proto_enumTypes[0]
}

func (x NodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeState.Descriptor instead.
func (NodeState) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_rpcs_proto_rawDescGZIP(), []int{0}
}

// 注册开发帐号
type DevRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountName   string                 `protobuf:"bytes,1,opt,name=accountName,proto3" json:"accountName,omitempty"` // 帐号名
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`       // 密码
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`                   // ip地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevRegister) Reset() {
	*x = DevRegister{}
	mi := &file_internal_protocol_rpcs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevRegister) ProtoMessage() {}

func (x *DevRegister) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_rpcs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevRegister.ProtoReflect.Descriptor instead.
func (*DevRegister) Descriptor() ([]byte, []int) {
	return file_internal_protocol_rpcs_proto_rawDescGZIP(), []int{0}
}

func (x *DevRegister) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *DevRegister) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DevRegister) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// 用户信息
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SdkId         int32                  `protobuf:"varint,1,opt,name=sdkId,proto3" json:"sdkId,omitempty"`       // sdk id
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`           // 包id
	OpenId        string                 `protobuf:"bytes,3,opt,name=openId,proto3" json:"openId,omitempty"`      // sdk的openid
	ServerId      int32                  `protobuf:"varint,4,opt,name=serverId,proto3" json:"serverId,omitempty"` // 所在游戏服id
	Uid           int64                  `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`           // 用户id
	Ip            string                 `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`              // 请求ip
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_protocol_rpcs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_rpcs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_internal_protocol_rpcs_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetSdkId() int32 {
	if x != nil {
		return x.SdkId
	}
	return 0
}

func (x *User) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *User) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *User) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *User) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *User) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

var File_internal_protocol_rpcs_proto protoreflect.FileDescriptor

const file_internal_protocol_rpcs_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/protocol/rpcs.proto\x12\x0fcherry.proto.pb\"[\n" +
	"\vDevRegister\x12 \n" +
	"\vaccountName\x18\x01 \x01(\tR\vaccountName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\"\x84\x01\n" +
	"\x04User\x12\x14\n" +
	"\x05sdkId\x18\x01 \x01(\x05R\x05sdkId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06openId\x18\x03 \x01(\tR\x06openId\x12\x1a\n" +
	"\bserverId\x18\x04 \x01(\x05R\bserverId\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\x03R\x03uid\x12\x0e\n" +
	"\x02ip\x18\x06 \x01(\tR\x02ip*/\n" +
	"\tNodeState\x12\b\n" +
	"\x04Open\x10\x00\x12\f\n" +
	"\bMaintain\x10\x01\x12\n" +
	"\n" +
	"\x06Closed\x10\x02B\x05Z\x03/pbb\x06proto3"

var (
	file_internal_protocol_rpcs_proto_rawDescOnce sync.Once
	file_internal_protocol_rpcs_proto_rawDescData []byte
)

func file_internal_protocol_rpcs_proto_rawDescGZIP() []byte {
	file_internal_protocol_rpcs_proto_rawDescOnce.Do(func() {
		file_internal_protocol_rpcs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_rpcs_proto_rawDesc), len(file_internal_protocol_rpcs_proto_rawDesc)))
	})
	return file_internal_protocol_rpcs_proto_rawDescData
}

var file_internal_protocol_rpcs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protocol_rpcs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_protocol_rpcs_proto_goTypes = []any{
	(NodeState)(0),      // 0: cherry.proto.pb.NodeState
	(*DevRegister)(nil), // 1: cherry.proto.pb.DevRegister
	(*User)(nil),        // 2: cherry.proto.pb.User
}
var file_internal_protocol_rpcs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protocol_rpcs_proto_init() }
func file_internal_protocol_rpcs_proto_init() {
	if File_internal_protocol_rpcs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_rpcs_proto_rawDesc), len(file_internal_protocol_rpcs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_rpcs_proto_goTypes,
		DependencyIndexes: file_internal_protocol_rpcs_proto_depIdxs,
		EnumInfos:         file_internal_protocol_rpcs_proto_enumTypes,
		MessageInfos:      file_internal_protocol_rpcs_proto_msgTypes,
	}.Build()
	File_internal_protocol_rpcs_proto = out.File
	file_internal_protocol_rpcs_proto_goTypes = nil
	file_internal_protocol_rpcs_proto_depIdxs = nil
}
