// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/protocol/sign_in.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 签到请求
type SignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	mi := &file_internal_protocol_sign_in_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_sign_in_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_sign_in_proto_rawDescGZIP(), []int{0}
}

func (x *SignInRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 签到响应
type SignInResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ContinuousDays int32                  `protobuf:"varint,2,opt,name=continuousDays,proto3" json:"continuousDays,omitempty"`  // 连续签到天数
	TodayReward    int32                  `protobuf:"varint,3,opt,name=todayReward,proto3" json:"todayReward,omitempty"`        // 今日奖励
	SignInDates    []int64                `protobuf:"varint,4,rep,packed,name=signInDates,proto3" json:"signInDates,omitempty"` // 已签到日期列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignInResponse) Reset() {
	*x = SignInResponse{}
	mi := &file_internal_protocol_sign_in_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInResponse) ProtoMessage() {}

func (x *SignInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_sign_in_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInResponse.ProtoReflect.Descriptor instead.
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_sign_in_proto_rawDescGZIP(), []int{1}
}

func (x *SignInResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SignInResponse) GetContinuousDays() int32 {
	if x != nil {
		return x.ContinuousDays
	}
	return 0
}

func (x *SignInResponse) GetTodayReward() int32 {
	if x != nil {
		return x.TodayReward
	}
	return 0
}

func (x *SignInResponse) GetSignInDates() []int64 {
	if x != nil {
		return x.SignInDates
	}
	return nil
}

// 签到状态
type SignInStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       int64                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	ContinuousDays int32                  `protobuf:"varint,2,opt,name=continuousDays,proto3" json:"continuousDays,omitempty"`
	HasSignedToday bool                   `protobuf:"varint,3,opt,name=hasSignedToday,proto3" json:"hasSignedToday,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignInStatus) Reset() {
	*x = SignInStatus{}
	mi := &file_internal_protocol_sign_in_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInStatus) ProtoMessage() {}

func (x *SignInStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_sign_in_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInStatus.ProtoReflect.Descriptor instead.
func (*SignInStatus) Descriptor() ([]byte, []int) {
	return file_internal_protocol_sign_in_proto_rawDescGZIP(), []int{2}
}

func (x *SignInStatus) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *SignInStatus) GetContinuousDays() int32 {
	if x != nil {
		return x.ContinuousDays
	}
	return 0
}

func (x *SignInStatus) GetHasSignedToday() bool {
	if x != nil {
		return x.HasSignedToday
	}
	return false
}

// 签到记录
type SignInRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerId        int64                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	LastSignInDate  string                 `protobuf:"bytes,2,opt,name=lastSignInDate,proto3" json:"lastSignInDate,omitempty"`
	ContinuousDays  int32                  `protobuf:"varint,3,opt,name=continuousDays,proto3" json:"continuousDays,omitempty"`
	TotalSignInDays int32                  `protobuf:"varint,4,opt,name=totalSignInDays,proto3" json:"totalSignInDays,omitempty"`
	TodayReward     int32                  `protobuf:"varint,5,opt,name=todayReward,proto3" json:"todayReward,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignInRecord) Reset() {
	*x = SignInRecord{}
	mi := &file_internal_protocol_sign_in_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRecord) ProtoMessage() {}

func (x *SignInRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_sign_in_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRecord.ProtoReflect.Descriptor instead.
func (*SignInRecord) Descriptor() ([]byte, []int) {
	return file_internal_protocol_sign_in_proto_rawDescGZIP(), []int{3}
}

func (x *SignInRecord) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *SignInRecord) GetLastSignInDate() string {
	if x != nil {
		return x.LastSignInDate
	}
	return ""
}

func (x *SignInRecord) GetContinuousDays() int32 {
	if x != nil {
		return x.ContinuousDays
	}
	return 0
}

func (x *SignInRecord) GetTotalSignInDays() int32 {
	if x != nil {
		return x.TotalSignInDays
	}
	return 0
}

func (x *SignInRecord) GetTodayReward() int32 {
	if x != nil {
		return x.TodayReward
	}
	return 0
}

// 签到结果
type SignInResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContinuousDays int32                  `protobuf:"varint,1,opt,name=continuousDays,proto3" json:"continuousDays,omitempty"`
	TodayReward    int32                  `protobuf:"varint,2,opt,name=todayReward,proto3" json:"todayReward,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignInResult) Reset() {
	*x = SignInResult{}
	mi := &file_internal_protocol_sign_in_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInResult) ProtoMessage() {}

func (x *SignInResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_sign_in_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInResult.ProtoReflect.Descriptor instead.
func (*SignInResult) Descriptor() ([]byte, []int) {
	return file_internal_protocol_sign_in_proto_rawDescGZIP(), []int{4}
}

func (x *SignInResult) GetContinuousDays() int32 {
	if x != nil {
		return x.ContinuousDays
	}
	return 0
}

func (x *SignInResult) GetTodayReward() int32 {
	if x != nil {
		return x.TodayReward
	}
	return 0
}

var File_internal_protocol_sign_in_proto protoreflect.FileDescriptor

const file_internal_protocol_sign_in_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/protocol/sign_in.proto\x12\x02pb\"+\n" +
	"\rSignInRequest\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x03R\bplayerId\"\x90\x01\n" +
	"\x0eSignInResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12&\n" +
	"\x0econtinuousDays\x18\x02 \x01(\x05R\x0econtinuousDays\x12 \n" +
	"\vtodayReward\x18\x03 \x01(\x05R\vtodayReward\x12 \n" +
	"\vsignInDates\x18\x04 \x03(\x03R\vsignInDates\"z\n" +
	"\fSignInStatus\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x03R\bplayerId\x12&\n" +
	"\x0econtinuousDays\x18\x02 \x01(\x05R\x0econtinuousDays\x12&\n" +
	"\x0ehasSignedToday\x18\x03 \x01(\bR\x0ehasSignedToday\"\xc6\x01\n" +
	"\fSignInRecord\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x03R\bplayerId\x12&\n" +
	"\x0elastSignInDate\x18\x02 \x01(\tR\x0elastSignInDate\x12&\n" +
	"\x0econtinuousDays\x18\x03 \x01(\x05R\x0econtinuousDays\x12(\n" +
	"\x0ftotalSignInDays\x18\x04 \x01(\x05R\x0ftotalSignInDays\x12 \n" +
	"\vtodayReward\x18\x05 \x01(\x05R\vtodayReward\"X\n" +
	"\fSignInResult\x12&\n" +
	"\x0econtinuousDays\x18\x01 \x01(\x05R\x0econtinuousDays\x12 \n" +
	"\vtodayReward\x18\x02 \x01(\x05R\vtodayRewardB\x05Z\x03/pbb\x06proto3"

var (
	file_internal_protocol_sign_in_proto_rawDescOnce sync.Once
	file_internal_protocol_sign_in_proto_rawDescData []byte
)

func file_internal_protocol_sign_in_proto_rawDescGZIP() []byte {
	file_internal_protocol_sign_in_proto_rawDescOnce.Do(func() {
		file_internal_protocol_sign_in_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_sign_in_proto_rawDesc), len(file_internal_protocol_sign_in_proto_rawDesc)))
	})
	return file_internal_protocol_sign_in_proto_rawDescData
}

var file_internal_protocol_sign_in_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_protocol_sign_in_proto_goTypes = []any{
	(*SignInRequest)(nil),  // 0: pb.SignInRequest
	(*SignInResponse)(nil), // 1: pb.SignInResponse
	(*SignInStatus)(nil),   // 2: pb.SignInStatus
	(*SignInRecord)(nil),   // 3: pb.SignInRecord
	(*SignInResult)(nil),   // 4: pb.SignInResult
}
var file_internal_protocol_sign_in_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protocol_sign_in_proto_init() }
func file_internal_protocol_sign_in_proto_init() {
	if File_internal_protocol_sign_in_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_sign_in_proto_rawDesc), len(file_internal_protocol_sign_in_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_sign_in_proto_goTypes,
		DependencyIndexes: file_internal_protocol_sign_in_proto_depIdxs,
		MessageInfos:      file_internal_protocol_sign_in_proto_msgTypes,
	}.Build()
	File_internal_protocol_sign_in_proto = out.File
	file_internal_protocol_sign_in_proto_goTypes = nil
	file_internal_protocol_sign_in_proto_depIdxs = nil
}
